// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn98nqPdCOrpE8LFKZT5zC2QZYwYhnK9k',
    appId: '1:121043285992:web:3b730b0197fbeb8a44d65d',
    messagingSenderId: '121043285992',
    projectId: 'convival-application',
    authDomain: 'convival-application.firebaseapp.com',
    storageBucket: 'convival-application.appspot.com',
    measurementId: 'G-32WV30RK6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs0cRxySsCRSqOhjow_wQwH9CyEkiOsTA',
    appId: '1:121043285992:android:8c629d3d47ccc97344d65d',
    messagingSenderId: '121043285992',
    projectId: 'convival-application',
    storageBucket: 'convival-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSvNo7HxUPjig0X6Ju5ZlmuOqr6o-wa9M',
    appId: '1:121043285992:ios:3aacf997372b8eb244d65d',
    messagingSenderId: '121043285992',
    projectId: 'convival-application',
    storageBucket: 'convival-application.appspot.com',
    iosClientId: '121043285992-idvoks7da411cnl23pot88k973iuibqt.apps.googleusercontent.com',
    iosBundleId: 'com.example.convivalapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSvNo7HxUPjig0X6Ju5ZlmuOqr6o-wa9M',
    appId: '1:121043285992:ios:610f65e5fc3e61ac44d65d',
    messagingSenderId: '121043285992',
    projectId: 'convival-application',
    storageBucket: 'convival-application.appspot.com',
    iosClientId: '121043285992-gqudetuqp9rm0il7atg3m3rchvgkftu7.apps.googleusercontent.com',
    iosBundleId: 'com.example.convivalapp.RunnerTests',
  );
}
